application:
  crossover:
    token: 430109:1564055978335:57f5167da6e473d9a1d41a9cf7b33dab
    teamId: 2952
    trackerApi: https://api.crossover.com/api/tracker/activity/groups?date={date}&fullTeam=true&groups=groups&refresh=false&teamId={teamId}&weekly=false
    checkInChatApi: https://api.crossover.com/api/productivity/managers/checkins?from={fromDate}&to={toDate}&teamId={teamId}
  candidate:
    hourPerDay: 7
    devTime: 70
    focusScore: 90
    intensityScore: 90
    deepWorkBlock: 3
    workBlocksLess: 6
    date: 2018-11-16
  google:
    spreedsheetId: 1EuXuVLd1qioRBdypdtcTZ869QqKuz30r4yMbNwJ9cUA
    sheetName: Index
